<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImageSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('images')->insert([
            [
                'file' => 'car (1).jpg',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'car (2).jpg',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'car (3).jpg',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'car (4).jpg',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'tour (1).jpg',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'tour (2).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'tour (3).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'tour (4).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (1).jpg',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (2).jpg',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (3).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (4).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (5).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (6).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (7).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (8).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (9).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (10).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (11).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (12).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (13).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (14).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'file' => 'blog (15).png',
                'path' => 'assets/imgs/page/',
                'alt' => 'Sample Image',
                'size' => '100 kb',
                'resolution' => '1920x2123', 
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
